version: '3.3'

volumes:
  pg_data:
  static:
  
services:
  db:
    container_name: hammer-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    container_name: hammer-back
    build: ./hammer_api/
    env_file: .env
    volumes:
      - static:/backend_static

  nginx:
    container_name: hammer-proxy
    build: ./infra
    env_file: .env
    ports:
      - 8050:80
    volumes:
      - static:/staticfiles
