# Generated by Django 4.2.23 on 2025-07-25 21:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authcode',
            options={'verbose_name': 'код авторизации', 'verbose_name_plural': 'Коды авторизации'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='authcode',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='verification_code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Код верификации'),
        ),
        migrations.AddConstraint(
            model_name='authcode',
            constraint=models.UniqueConstraint(fields=('phone_number', 'verification_code'), name='unique_code'),
        ),
    ]
