# Generated by Django 4.2.23 on 2025-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authcode',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='authcode',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='authcode',
            name='confirmation_code',
            field=models.CharField(default=1234, max_length=4, unique=True, verbose_name='Код авторизации'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='authcode',
            constraint=models.UniqueConstraint(fields=('phone_number', 'confirmation_code'), name='unique_code'),
        ),
    ]
