# Generated by Django 4.2.23 on 2025-07-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_authcode_unique_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_invite',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_received', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('user', 'invited_by'), name='unique_invite'),
        ),
    ]
