# Generated by Django 4.2.23 on 2025-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_invitation_unique_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата генерации кода'),
        ),
    ]
