# Generated by Django 4.2.23 on 2025-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_authcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Необязательное поле. 150 символов или меньше.', max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
